name: Publish to Zero-OS Hub
description: Build and publish flist from your workflow
author: ThreeFold Tech
inputs:
  action:
    required: true
    description: |
        Action do you want to do, this is required and needs
        to be one of theses values:
         - publish: create and upload an flist
         - upload: upload a .tar.gz archive directly
         - promote: promote an flist on the hub to another repository
         - rename: rename one of your flist to a new name
         - symlink: create a symlink on the hub
         - crosslink: create a cross-repository symlink on the hub
         - delete: delete one of your flist
         - readlink: read target name of a symlink
         - merge: merge targets into name
         - tag: tag an flist (untag supported as well)
         - crosstag: create a link to a tag

        All actions needs a 'name' and 'token' argument. For symlink
        and promote, the name is the source name, the input 'target' is
        the destination repository/filename or the linkname.

        When tagging, 'target' is the destination of the link (eg: user/target.flist)
        and 'name' is your tag and link name (eg: v1.0.0/link.flist)

        When crosstagging, 'name' is link name in your repository and 'target' is
        the destination link (eg: user/destination.flist)

        When using readlink, result will be put on 'linkpoint' output
        variable.

        When using merge action, name is the result filename and target
        should be all flists to merge togethers, separated by space, eg:

            name: hello.flist
            target: tf-bootable/ubuntu:18.04.flist maxux/my-service.flist

        this will merge 'maxux/my-service.flist' inside 'tf-bootable/ubuntu:18.04.flist'
        and save it as 'yourname/hello.flist'

  name:
    description: The name of your flist file
    required: true
  root:
    description: The root directory to be published
    default: /github/workspace
  token:
    description: hub.grid.tf itsyou online token
  threefold:
    description: hub.grid.tf threefold connect token
  user:
    description: |
        The username to switch when using a jwt allowing that.
        This is required when promoting.
  target:
    description: |
        For action 'symlink' and 'promote', this is the link name
        or the destination repository/filename.

        For action 'rename', this is the new name of your flist

        For 'crosslink', this should be 'repository/filename' format

        For tagging, this is the destination link (format repository/filename)
        
        For 'merge' action, this is a list of flist separated by space,
        formatted by full name (repository/flist, eg: 'maxux/my-file.flist')

outputs:
  linkpoint:
    description: readlink target name

runs:
  using: 'docker'
  image: 'docker://maxux/zflist:development-v2'
  entrypoint: /usr/local/bin/zflist-publish
  env:
    ZFLIST_MNT: /tmp/newflist
  
